on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DEBIAN_FRONTEND: noninteractive
      LMOD_VERSION: 8.7.4

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt install -y curl python3 python3-distutils python3-pip
      - run: curl -OL https://github.com/surak/Lmod/releases/download/${LMOD_VERSION}/lmod_${LMOD_VERSION}_all.deb
      - run: sudo apt install -y ./lmod_${LMOD_VERSION}_all.deb
       # debianutils provides 'which' command
      - run: sudo apt install -y bzip2 debianutils diffutils file gcc g++ git gzip libibverbs-dev openssl libssl3 libssl1.1 libssl-dev make patch tar unzip xz-utils
      - run: python3 -m pip install archspec easybuild rich
      
      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/.local/easybuild
          key: ${{ runner.os }}-root-2 # -${{ hashFiles('duckdb.eb') }}

      - shell: bash
        name: Build DuckDB (dry-run)
        run: |
          . /usr/lmod/lmod/init/bash
          eb duckdb.eb --robot --trace --dry-run
      - name: BinUtils
        shell: bash
        run: |
          . /usr/lmod/lmod/init/bash
          eb binutils-2.32.eb --robot --trace
          
      - run: |
          echo 'wrap_system_openssl = False' >> /home/runner/.local/easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.eb
          cat /home/runner/.local/easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.eb

      - name: OpenSSL
        shell: bash
        timeout-minutes: 120
        run: |
          . /usr/lmod/lmod/init/bash
          eb OpenSSL-1.1.eb --robot --trace

      - shell: bash
        name: GCCcore
        timeout-minutes: 240
        run: |
          . /usr/lmod/lmod/init/bash
          eb GCCcore-12.2.0.eb --robot --trace

      - shell: bash
        name: Build DuckDB
        timeout-minutes: 240
        run: |
          . /usr/lmod/lmod/init/bash
          eb duckdb.eb --robot --trace
      - run: |
          shopt -s nullglob
          for f in "/tmp/eb-*/easybuild-*.log"; do cat $f; done
        shell: bash
        if: always()
        name: Dump logs

      - name: Save cache
        id: cache-save
        if: always()
        uses: actions/cache/save@v3
        with:
          path: /home/runner/.local/easybuild
          key: ${{ runner.os }}-root-3
