on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/easybuilders/ubuntu-20.04:latest
    
    steps:
      - uses: actions/checkout@v3
      - run: eb duckdb.easyconfig
