on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DEBIAN_FRONTEND: noninteractive
      LMOD_VERSION: 8.7.4

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt install -y curl python3 python3-distutils python3-pip
      - run: curl -OL https://github.com/surak/Lmod/releases/download/${LMOD_VERSION}/lmod_${LMOD_VERSION}_all.deb
      - run: sudo apt install -y ./lmod_${LMOD_VERSION}_all.deb
       # debianutils provides 'which' command
      - run: sudo apt install -y bzip2 debianutils diffutils file gcc g++ git gzip libibverbs-dev openssl libssl-dev make patch tar unzip xz-utils
      - run: python3 -m pip install archspec easybuild rich
      - shell: bash
        name: Build DuckDB (dry-run)
        run: |
          . /usr/lmod/lmod/init/bash
          eb duckdb.easyconfig --robot --trace --dry-run >> $GITHUB_STEP_SUMMARY
      - shell: bash
        name: Build GCC
        timeout-minutes: 12
        run: |
          . /usr/lmod/lmod/init/bash
          eb GCC-8.3.0.eb --robot --trace
      - shell: bash
        name: Build DuckDB
        timeout-minutes: 12
        run: |
          . /usr/lmod/lmod/init/bash
          eb duckdb.easyconfig --robot --trace
